config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root 'pages#home'
  post 'calculators/calculate' => 'calculators#calculate'

  match '/contact', to: 'contacts#new', via: 'get'
  match '/offerte-online', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create], :path => 'contact'

  get '/admin' => 'admin#index'
  get '/materialen' => 'pages#materialen'
  get ':slug' => 'pages#show'
  
  put '/cookies' => 'pages#cookie_info'
  post '/cookies' => 'pages#cookie_info'
  get '/cookies' => 'pages#show'

  namespace :admin do
    resources :articles do
      member do
        get 'preview'        
      end
    end
    resources :media
    resources :projects do
      resources :cushions
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	@article_statuses = {0=> 'Niewidoczny', 1=>'Widoczny'}
	extend FriendlyId
	friendly_id :title, use: :slugged
	has_many :media
	belongs_to :category
	def save
    if self.template == "0"
      self.template = nil
    end
		self.slug = slug.parameterize
		super
	end
	def should_generate_new_friendly_id? #generate slug when provided blank from form (it extending so super invoked)
		slug.blank? || super
	end
	def to_param #override FriendlyId to_param
		id
	end
	def self.article_statuses
		@article_statuses
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :subject, :validate => true
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => %(#{subject}),
      :to => "info@marinestofferingen.nl",
      :from => %("#{name}" <info@marinestofferingen.nl>),
      :reply_to => %("#{name}" <#{email}>)
    }
  end
end

app/models/cushion.rb
class Cushion < ActiveRecord::Base
	belongs_to :project
	def calculate_price
		self.width.to_f + self.height.to_f
	end
	def save
		self.price = self.calculate_price
		super
	end
end

app/models/medium.rb
class Medium < ActiveRecord::Base
  has_attached_file :attachment,
    :path => 'public/images/:attachment/:id/:style/:filename',    
    :url => "http://#{Rails.application.secrets.domain_name}/images/:attachment/:id/:style/:filename",
    :styles => { :large => "800x800>", :medium => "400x400>", :thumb => "200x200>", :gallery_thumb => '760x500#', :slide => '1180x590#' },
    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
  belongs_to :article
end

app/models/project.rb
class Project < ActiveRecord::Base
	@project_types_hash = {1=>'Poduszki', 2=>'Plandeki',9=>'Inne takie szmakie'}
	has_many :cushions
	has_many :veranda_parts

	def self.project_types
		@project_types_hash
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/veranda_part.rb
class VerandaPart < ActiveRecord::Base
	belongs_to :project
	@fastening_types = {'drukknoppen'=>1,'Tournquiets'=>2,'Minax'=>3,'Tenax'=>4,'Zamek'=>5} #=30€ (za element)}
	def self.fastening_types
		@fastening_types
	end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  layout 'application', only: [:preview]
	expose(:articles)
  expose(:article, attributes: :article_params)
	def index
	end
	def new
	end
	def edit
	end
	def create
		if article.save
			redirect_to edit_admin_article_path article.id
		end
	end
	def update
		if article.save
      if not params[:article][:media_array].nil?
  			params[:article][:media_array].each do |m|
  				article.media.create(:attachment => m)
  			end
      end
			redirect_to edit_admin_article_path article.id
		end
		# if @user.save
  #    # params[:avatar] will be an array.
  #    # you can check total number of photos selected using params[:avatar].count
  #     params[:avatar].each do |picture|      

  #       @user.images.create(:avatar=> picture)
  #       # Don't forget to mention :avatar(field name)

  #     end
    # end
	end
	def destroy
		if article.destroy
			redirect_to admin_articles_path
		end
	end

  def preview
    @page = article
    if @page.template == nil
      render "pages/#{@page.slug}"
    else
      render 'pages/show'
    end
  end

	private

	def article_params
		params.require(:article).permit(:title, :slug, :content, :status, :author_id, :category_id, :published_at, :media_array, :template)
	end
end

app/controllers/admin/media_controller.rb
class Admin::MediaController < AdminController
	
	expose(:media)
	expose(:medium, attributes: :medium_params)

	def new
	end
	def edit
	end
	def index
	end
	def create
		if medium.save
			redirect_to edit_admin_medium_path medium.id
		end
	end
	def update
		if medium.save
			redirect_to edit_admin_medium_path medium.id
		end
	end

	private

	def medium_params
		params.require(:medium).permit(:title, :slug, :description, :attachment)
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!
  before_filter :authenticate_admin
  def authenticate_admin
    unless current_user.try(:is_admin?)
      render :status => :forbidden, :text => "Brak uprawnień do przeglądania tej strony!"
    end
  end
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
	
	def index
	end

	def calculate
		@x = params[:project]
		@y = @x[:height1].to_f + @x[:height2].to_f
	end

	private
	
	def calculator_params
		params.require(:height1, :height2, :width, :belt_thickness, :overlap)
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    if request.env['PATH_INFO'] == '/offerte-online'
      @page = Article.find_by_slug('offerte-online')
    else
      @page = Article.find_by_slug('contact')
    end
  end

  def create
    @contact = Contact.new(params[:contact])
    @page = Article.find_by_slug('contact')
    @contact.request = request
    if @contact.deliver
      flash.now[:info] = 'Bedankt voor uw bericht. Wij zullen zo snel mogelijk contact met u nemen.'
    else
      flash.now[:error] = 'Bericht kan niet verzonden worden.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  protect_from_forgery with: :exception, except: :cookie_info

  def show
    @page = Article.find_by_slug(params[:slug])
    if @page.nil? or @page.status == 0
      raise ActionController::RoutingError.new('Not Found')
    else
      @title = @page.title != 'Home' ? "#{@page.title} - " : ''
      if not @page.template?
        render "pages/#{params[:slug]}"
      end
    end
  end

  def home
    @page = Article.find_by_slug('home')
    @posts = Category.find_by_name('Post').articles.limit(6)
    @advantages = Category.find_by_name('Voordeelen').articles.limit(6)
    @products = Category.find_by_name('Product').articles.limit(4)
    @slides = Article.find_by_slug('home-slider')
  end

  def materialen
    @page = Article.find_by_slug('Materialen')
    @materials = Category.find_by_name('Materialen').articles
  end

  def cookie_info
    if request.put?
      if cookies[:cookie_info].nil?
        cookies[:cookie_info] = { value: 'accepted', expires: 1.month.from_now }
      render plain: "#{!cookies[:cookie_info].nil?}"
      end
    elsif request.post?
      render plain: "#{!cookies[:cookie_info].nil?}"
    end
  end

  private

  def page_params
    params.require(:slug)
  end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/cushions_helper.rb
module Admin::CushionsHelper
end

app/helpers/admin/media_helper.rb
module Admin::MediaHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculators_helper.rb
module CalculatorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/media/_form.html.haml
= image_tag medium.attachment.url(:thumb)
= simple_form_for [:admin, medium], :html => { :multipart => true } do |f|
	.col-md-8
		.form-horizontal
			= f.input :title, input_html: { class: 'input-lg' }
			= f.input :slug
			= f.input :description, input_html: { class: 'ckeditor' }
			= f.file_field :attachment, :wrapper => "vertical_form"
			.form-group
				.col-sm-10.col-sm-offset-2
					= f.submit 'Zapisz', :class => "btn btn-primary"

app/views/admin/media/edit.html.haml
%h3 Edytuj media
=render "form"

app/views/admin/media/index.html.haml
.row.page-header
  .col-md-6
    %h3 Media
  .col-md-6.text-right
    = link_to 'Dodaj nowe', new_admin_medium_path, class: 'btn btn-info'
.row
  - media.each do |m|
    .col-md-3
      = link_to edit_admin_medium_path(m.id) do 
        = image_tag m.attachment.url(:gallery_thumb), class: "img-thumbnail img-responsive"

app/views/admin/media/new.html.haml
%h3 Dodaj nowe media
=render "form"

app/views/calculators/calculate.html.haml
%h1
	Calc
%p=@y

app/views/calculators/index.html.haml
%h1
	Kalkulator
= simple_form_for :project, :url => calculators_calculate_path do |f|
	= f.input :height1, label: 'Wysokość 1'
	= f.input :height2, label: 'Wysokość 2'
	= f.input :width, label: 'Szerokość'
	= f.input :belt_thickness, collection: 6..10, label: 'Grubość paska'
	= f.input :overlap, collection: (5..25).step(5), label: 'Zakładka'
	= f.submit

app/views/contacts/create.html.haml
= render 'layouts/top'
%section.elements
  .container
    .sixteen.colums
      - flash.each do |key, value|
        %div{ :class => "alert #{key}" }
          %p= value

app/views/contacts/new.html.haml
= render 'layouts/top'
<section class="contact">
<div class="container">
- if @page.slug == 'contact'
  <!-- Sidebar Start -->
  <div class="four columns">
  <div class="contact-sidebar">
  = raw @page.content
  </div>
  <!-- Sidebar End -->
  </div>
  <div class="twelve columns">
  <!-- Map -->
  <div id="google-map">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2434.113161637118!2d5.245459315256141!3d52.40462527979256!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c61777f9667b1d%3A0x9ec4d83c2d06a618!2sHefbrugweg+12%2C+1332+AN+Almere!5e0!3m2!1spl!2snl!4v1451490008296" width="600" height="450" frameborder="0" style="border:0" allowfullscreen=""></iframe><br>
  </div>
- else
  <div class="two columns" style="padding-top:1px;"> </div>
  <div class="twelve columns">
  = raw @page.content
<!-- Contact Form -->
<div class="form">
= simple_form_for @contact, :html => {:class => 'clearfix' } do |f|
  .field= f.input :name, :required => true, :wrapper => false, :label => 'Naam', :class => 'text'
  .field= f.input :email, :required => true, :wrapper => false, :class => 'text'
  .field.field-last= f.input :subject, :required => true, :wrapper => false, :label => 'Onderwerp', :class => 'text'
  = f.input :message, :as => :text, :required => true, :wrapper => false, :label => false, :label => false
  .hidden
    = f.input :nickname, :hint => 'Leave this field blank!'
  = f.button :submit, 'Verstuur bericht', :class=> "btn", :id => "send"
</div>
<!-- Contact Form / End -->
</div>
</div>
</section>