config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root 'pages#home'
  post 'calculators/calculate' => 'calculators#calculate'

  match '/contact', to: 'contacts#new', via: 'get'
  match '/offerte-online', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create], :path => 'contact'

  get '/admin' => 'admin#index'
  get '/materialen' => 'pages#materialen'
  get ':slug' => 'pages#show'
  
  put '/cookies' => 'pages#cookie_info'
  post '/cookies' => 'pages#cookie_info'
  get '/cookies' => 'pages#show'

  namespace :admin do
    resources :articles do
      member do
        get 'preview'        
      end
    end
    resources :media
    resources :projects do
      resources :cushions
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	@article_statuses = {0=> 'Niewidoczny', 1=>'Widoczny'}
	extend FriendlyId
	friendly_id :title, use: :slugged
	has_many :media
	belongs_to :category
	def save
    if self.template == "0"
      self.template = nil
    end
		self.slug = slug.parameterize
		super
	end
	def should_generate_new_friendly_id? #generate slug when provided blank from form (it extending so super invoked)
		slug.blank? || super
	end
	def to_param #override FriendlyId to_param
		id
	end
	def self.article_statuses
		@article_statuses
	end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  layout 'application', only: [:preview]
	expose(:articles)
  expose(:article, attributes: :article_params)
	def index
	end
	def new
	end
	def edit
	end
	def create
		if article.save
			redirect_to edit_admin_article_path article.id
		end
	end
	def update
		if article.save
      if not params[:article][:media_array].nil?
  			params[:article][:media_array].each do |m|
  				article.media.create(:attachment => m)
  			end
      end
			redirect_to edit_admin_article_path article.id
		end
		# if @user.save
  #    # params[:avatar] will be an array.
  #    # you can check total number of photos selected using params[:avatar].count
  #     params[:avatar].each do |picture|      

  #       @user.images.create(:avatar=> picture)
  #       # Don't forget to mention :avatar(field name)

  #     end
    # end
	end
	def destroy
		if article.destroy
			redirect_to admin_articles_path
		end
	end

  def preview
    @page = article
    if @page.template == nil
      render "pages/#{@page.slug}"
    else
      render 'pages/show'
    end
  end

	private

	def article_params
		params.require(:article).permit(:title, :slug, :content, :status, :author_id, :category_id, :published_at, :media_array, :template)
	end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_form.html.haml
= simple_form_for [:admin, article], :html => { :multipart => true }  do |f|
	.col-md-8
		.form-horizontal
			= f.input :title, input_html: { class: 'input-lg' }
			= f.input :slug
			= f.input :content, input_html: { class: 'ckeditor' }
			= f.input :media_array, as: :file, input_html: { multiple: true }
			.form-group
				.col-sm-10.col-sm-offset-2
					= f.submit 'Zapisz artykuł', class: 'btn btn-primary'
	.col-md-4
		= f.input :category_id, label: 'Kategoria', collection: Category.all.map{|c| [c.name, c.id]}, prompt: 'Wybierz kategorię', selected: article.category_id, wrapper: 'vertical_form', default: 0
		= f.input :template, label: 'Template', collection: Dir.glob("app/views/pages/templates/*.haml").unshift("0").map!{|f| [f.sub('app/views/pages/templates/','').sub('.html.haml','').gsub('_',' ').sub(/0{1}/,'Brak').strip.capitalize, f.sub('app/views','').sub('.html.haml','').gsub('/_','/')]}, selected: article.template, wrapper: 'vertical_form', default: 0
		= f.input :status, label: 'Status', collection: Article::article_statuses.map{|s| [s[1],s[0]]}, selected: article.status, wrapper: 'vertical_form'
		= f.input :published_at, as: :string, wrapper: 'vertical_form'

app/views/admin/articles/edit.html.haml
.row
  .page-header.col-md-12
    %h3 Edytuj treść
    = link_to preview_admin_article_path(article.id), class: 'btn btn-sm btn-info' do
      %i.glyphicon.glyphicon-search
      Podgląd
    %hr
.row.col-md-12
  = render 'form'
.row.col-md-12
  %hr
  %h4 Załączone media
  .row
    - article.media.each do |m|
      .col-lg-2.col-md-3.col-sm-4
        = link_to edit_admin_medium_path(m.id) do 
          = image_tag m.attachment.url(:gallery_thumb), class: "img-thumbnail img-responsive"

app/views/admin/articles/index.html.haml
.row.page-header
  .col-md-6
    %h3 Artykuły
  .col-md-6.text-right
    = link_to 'Dodaj nowy', new_admin_article_path, class: 'btn btn-info'
%table.table.table-striped
  %thead
    %tr
      %th #ID
      %th Nazwa
      %th Slug
      %th Kategoria
      %th Template
      %th.text-right Zmodyfikowano
      %th.text-right Akcje
  %tbody
    - articles.each do |article|
      %tr
        %td= article.id
        %td= link_to article.title, edit_admin_article_path(article.id)
        %td= article.slug
        %td= article.category.nil? ? 'Brak' : article.category.name
        %td= article.template.nil? ? 'Brak' : article.template.sub('/pages/templates/','').capitalize
        %td.text-right= article.updated_at.strftime("%d %b %Y, %H:%M")
        %td.text-right
          =link_to admin_article_path(article.id), method: "delete", data: {confirm: "Czy na pewno usunąć?"}, class: "btn btn-danger btn-xs" do
            %i.glyphicon.glyphicon-trash
            Usuń

app/views/admin/articles/new.html.haml
%h3 Nowy artykuł
= render 'form'