config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root 'pages#home'
  post 'calculators/calculate' => 'calculators#calculate'

  match '/contact', to: 'contacts#new', via: 'get'
  match '/offerte-online', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create], :path => 'contact'

  get '/admin' => 'admin#index'
  get '/materialen' => 'pages#materialen'
  get ':slug' => 'pages#show'
  
  put '/cookies' => 'pages#cookie_info'
  post '/cookies' => 'pages#cookie_info'
  get '/cookies' => 'pages#show'

  namespace :admin do
    resources :articles do
      member do
        get 'preview'        
      end
    end
    resources :media
    resources :projects do
      resources :cushions
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	@article_statuses = {0=> 'Niewidoczny', 1=>'Widoczny'}
	extend FriendlyId
	friendly_id :title, use: :slugged
	has_many :media
	belongs_to :category
	def save
    if self.template == "0"
      self.template = nil
    end
		self.slug = slug.parameterize
		super
	end
	def should_generate_new_friendly_id? #generate slug when provided blank from form (it extending so super invoked)
		slug.blank? || super
	end
	def to_param #override FriendlyId to_param
		id
	end
	def self.article_statuses
		@article_statuses
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :subject, :validate => true
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => %(#{subject}),
      :to => "info@marinestofferingen.nl",
      :from => %("#{name}" <info@marinestofferingen.nl>),
      :reply_to => %("#{name}" <#{email}>)
    }
  end
end

app/models/cushion.rb
class Cushion < ActiveRecord::Base
	belongs_to :project
	def calculate_price
		self.width.to_f + self.height.to_f
	end
	def save
		self.price = self.calculate_price
		super
	end
end

app/models/medium.rb
class Medium < ActiveRecord::Base
  has_attached_file :attachment,
    :path => 'public/images/:attachment/:id/:style/:filename',    
    :url => "http://#{Rails.application.secrets.domain_name}/images/:attachment/:id/:style/:filename",
    :styles => { :large => "800x800>", :medium => "400x400>", :thumb => "200x200>", :gallery_thumb => '760x500#', :slide => '1180x590#' },
    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
  belongs_to :article
end

app/models/project.rb
class Project < ActiveRecord::Base
	@project_types_hash = {1=>'Poduszki', 2=>'Plandeki',9=>'Inne takie szmakie'}
	has_many :cushions
	has_many :veranda_parts

	def self.project_types
		@project_types_hash
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/veranda_part.rb
class VerandaPart < ActiveRecord::Base
	belongs_to :project
	@fastening_types = {'drukknoppen'=>1,'Tournquiets'=>2,'Minax'=>3,'Tenax'=>4,'Zamek'=>5} #=30€ (za element)}
	def self.fastening_types
		@fastening_types
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!
  before_filter :authenticate_admin
  def authenticate_admin
    unless current_user.try(:is_admin?)
      render :status => :forbidden, :text => "Brak uprawnień do przeglądania tej strony!"
    end
  end
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
	
	def index
	end

	def calculate
		@x = params[:project]
		@y = @x[:height1].to_f + @x[:height2].to_f
	end

	private
	
	def calculator_params
		params.require(:height1, :height2, :width, :belt_thickness, :overlap)
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    if request.env['PATH_INFO'] == '/offerte-online'
      @page = Article.find_by_slug('offerte-online')
    else
      @page = Article.find_by_slug('contact')
    end
  end

  def create
    @contact = Contact.new(params[:contact])
    @page = Article.find_by_slug('contact')
    @contact.request = request
    if @contact.deliver
      flash.now[:info] = 'Bedankt voor uw bericht. Wij zullen zo snel mogelijk contact met u nemen.'
    else
      flash.now[:error] = 'Bericht kan niet verzonden worden.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  protect_from_forgery with: :exception, except: :cookie_info

  def show
    @page = Article.find_by_slug(params[:slug])
    if @page.nil? or @page.status == 0
      raise ActionController::RoutingError.new('Not Found')
    else
      @title = @page.title != 'Home' ? "#{@page.title} - " : ''
      if not @page.template?
        render "pages/#{params[:slug]}"
      end
    end
  end

  def home
    @page = Article.find_by_slug('home')
    @posts = Category.find_by_name('Post').articles.limit(6)
    @advantages = Category.find_by_name('Voordeelen').articles.limit(6)
    @products = Category.find_by_name('Product').articles.limit(4)
    @slides = Article.find_by_slug('home-slider')
  end

  def materialen
    @page = Article.find_by_slug('Materialen')
    @materials = Category.find_by_name('Materialen').articles
  end

  def cookie_info
    if request.put?
      if cookies[:cookie_info].nil?
        cookies[:cookie_info] = { value: 'accepted', expires: 1.month.from_now }
      render plain: "#{!cookies[:cookie_info].nil?}"
      end
    elsif request.post?
      render plain: "#{!cookies[:cookie_info].nil?}"
    end
  end

  private

  def page_params
    params.require(:slug)
  end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/cushions_helper.rb
module Admin::CushionsHelper
end

app/helpers/admin/media_helper.rb
module Admin::MediaHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculators_helper.rb
module CalculatorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/index.html.haml
%h1
	= 'Witaj ' + current_user.email

app/views/layouts/_admin_top.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    %ul.nav.navbar-nav
      %li
        = link_to "Treści", admin_articles_path
    %ul.nav.navbar-nav.navbar-right
      %li
        = link_to destroy_user_session_path, method: :delete do
          %i.glyphicon.glyphicon-log-out
          Logout

app/views/layouts/_footer.html.erb
<footer>
	<section id="footer-main">
		<div class="container">
			<div class="sixteen columns">
				<p><i class="icon-map-marker"></i><strong>Adres: </strong>Hefbrugweg&nbsp;12, 1332&nbsp;AN&nbsp;Almere
				<i class="icon-phone"></i><strong>Telefoon: </strong><a href="tel:+31641912754">0641912754</a></li>
				<i class="icon-envelope"></i><strong>E-mail: </strong><a href="mailto:info@marinestofferingen.nl">info@marinestofferingen.nl</a></p>
			</div>	
		</div>
	</section>	
	<section class="footer-bar">
		<div class="container">
			<div class="eight columns">
				<div class="footer-logo"><img src="/images/logo-white.svg" alt="Marine Stofferingen" title="Marine Stofferingen"><span><%=Time.now.strftime("\%Y")%> © Copyright Marine Stofferingen.</span></div>
			</div>
			<!-- <div class="eight columns">
				<ul class="footer-links">
					<li><a href="#"><i class="icon-twitter"></i></a></li>
					<li><a href="#"><i class="icon-facebook"></i></a></li>
					<li><a href="#"><i class="icon-linkedin"></i></a></li>
					<li><a href="#"><i class="icon-pinterest"></i></a></li>
					<li><a href="#"><i class="icon-google-plus"></i></a></li>
				</ul>
			</div> -->
		</div>
	</section>
</footer>

app/views/layouts/_header.html.erb
<div class="contact-container">
	<div class="container">
	</div>
</div>
<div class="logo-container">
	<div class="container">
	
		<!-- Mobile Only Menu Button  -->
		<a href="#menu" class="menu-trigger"><i class="icon-reorder"></i></a>
		
		<!-- Logo  -->	
		<a class="logo" href="/"><img src="/images/logo.svg" alt="Marine Stofferingen" title="Marine Stofferingen"></a>
		
		<p class="call"><a href="tel:+31641912754"><i class="icon-phone"></i> 0641912754</a></p>
	</div>
</div>
<header class="menu">
	<div class="container">
		
		<!-- Navigation -->		
		<nav>
			<ul class="navigation">
				<li class="search"><input class="searchform" type="search" value="" placeholder="Search"></li>
				<li><a href="/">Home</a></li>
				<li><a href="/buiskap">Buiskap</a></li>
				<li><a href="/biminitop">Biminitop</a></li>
 				<li><a href="/afdekzeilen">Afdekzeilen</a></li>
 				<li><a href="/stoffering">Stoffering</a></li>
				<li><a href="/verandazeilen">Verandazeilen</a></li>
				<li><a href="/werkwijze">Werkwijze</a></li>
				<li><a href="/contact">Contact</a></li>		
			</ul>
		</nav>
	</div><!-- End of container -->
</header>

app/views/layouts/_top.html.haml
.page-title
  .container
    .twelve.columns
      %h1= @page.title
    %nav.four.columns
      %ul.breadcrumbs
        %li
          = link_to "Home", "/"
        %li
          %i.icon-angle-right
        %li= @page.title

app/views/layouts/admin.html.haml
!!!
%html
	%head
		%title Admin
		= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true
		= csrf_meta_tags
		<meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=1.0">
	%body
		= render "layouts/admin_top"
		.container-fluid#main
			.col-md-12
				= yield
		<script>
		var CKEDITOR_BASEPATH = '/js/ckeditor/';
		</script>
		= javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/application.html.haml
!!!
%html
    %head
        %title #{@title} #{Rails.application.secrets.app_title}
        %link{:rel => "stylesheet", :href => "/css/style.css"}/
        %link{:rel => "stylesheet", :href => "/css/colors/11.css"}/
        = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
        = csrf_meta_tags
        <meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=1.0">
    %body
        = render 'layouts/header'
        = yield
        = render 'layouts/footer'
        = javascript_include_tag 'application', 'data-turbolinks-track' => true
        <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-62678327-1', 'auto');
        ga('send', 'pageview');
        </script>

app/views/layouts/devise.html.haml
!!!
%html
		%head
				%title dasasx
				%link{:rel => "stylesheet", :href => "/css/style.css"}/
				%link{:rel => "stylesheet", :href => "/css/colors/1.css"}/
				= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
				= javascript_include_tag 'application', 'data-turbolinks-track' => true
				= csrf_meta_tags
				<meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=1.0">
		%body
				= render 'layouts/header'
				= yield
				= render 'layouts/footer'

app/views/pages/_gallery.html.haml
%section#portfolio
	.container
		%ul#portfolio-list.isotope
			- @page.media.each do |image|
				%li.one-third.column.item.branding.isotope-item{ :style => "position:relative" }
					%figure
						.hold.big
							= link_to image.attachment.url, :class => "isotope swipebox" do
								= image_tag image.attachment.url(:gallery_thumb), :alt => image.title
							/ = link_to "sdxsadx", :class => "hover-link" do
							/	 %i.icon-link
						/ %figcaption.item-description
						/	%h5 Image
						/	%span Description

app/views/pages/_gallery4.html.haml
%section#portfolio
	.container
		%ul#portfolio-list.isotope
			- @media.each do |image|
				%li.one-fourth.column.item.branding.isotope-item{ :style => "position:relative" }
					%figure
						.hold.big
							= link_to image.attachment.url, :class => "isotope swipebox" do
								= image_tag image.attachment.url(:gallery_thumb), :alt => image.title
							/ = link_to "sdxsadx", :class => "hover-link" do
							/	 %i.icon-link
						/ %figcaption.item-description
						/	%h5 Image
						/	%span Description

app/views/pages/about.html.haml
.page-title
	.container
		.twelve.columns
			%h1 About
			%p
				Marine Stofferingen zeilmakerij in Almere voor watersport en buitenleven.
		%nav.four.columns
			%ul.breadcrumbs
				%li
					= link_to "Home", "/"
				%li
					%i.icon-angle-right
				%li About
%section#typography
	.container
		.sixteen.columns
			%article
				%h2 Onze voordelen
		.two-thirds.columns
			%ul.serviceboxes
				%li
					.service-icon
						= image_tag "icons/unused/check.png", :alt => "" 
					%h3 Top kwaliteit producten
				%li
					.service-icon
						= image_tag "icons/unused/graph.png", :alt => "" 
					%h3 Altijd op maat gemaakt
				%li
					.service-icon
						= image_tag "icons/unused/clock.png", :alt => "" 
					%h3 Snelle levering
		.sixteen.columns		
			%article
				%p
					Marine Stofferingen is een bedrijf die zich specialiseerd in het maken:
				%ul.check-list
					%li RVS en ALU Frames
					%li cabriokap
					%li biminitop
					%li sprayhood
					%li boottenten
					%li kuiptenten
					%li afdekzeilen
					%li hoezen
					%li verandazeilen
					%li voortenten
					%li loungekussens
					%li scheepstoffering
/ %section#portfolio
/ 	.container
/ 		%ul#portfolio-list.isotope
/ 			- @images.each do |image|
/ 				%li.one-third.column.item.branding.isotope-item{ :style => "position:relative" }
/ 					= link_to "", "as", :class => "isotope"
/ 					%figure
/ 						= link_to "", "as", :class => "isotope"
/ 						.hold.big
/ 							= link_to "asx", :class => "isotope" do
/ 								= image_tag image.gsub("public/images/", ""), :alt => "aaa"
/ 							= link_to "sxsx", :class => "hover-zoom swipebox" do
/ 								%i.icon-search
/ 							= link_to "sdxsadx", :class => "hover-link" do
/ 								%i.icon-link
/ 						%figcaption.item-description
/ 							%h5 Image
/ 							%span Description

app/views/pages/biminitop.html.haml
.page-title
	.container
		.twelve.columns
			%h1 Biminitop
		%nav.four.columns
			%ul.breadcrumbs
				%li
					= link_to "Home", "/"
				%li
					%i.icon-angle-right
				%li Biminitop
%section#typography
	.container
		.sixteen.columns
			%article
				%h2 Biminitop
				%p Bij ons koop je geen standaard bimini, elke keer makken wij apartre ontwerp, frame aan hand van uw wensen en type boot. Beste kwaliteit Stoffen kunnen heel goed tegen de Zon en Water. Biminitop kunt u zelf inmeten en monteren. Dat kunnen wij ook doen, of op jou haven, of breng maar boot bij ons.
			%article
				%p
					In het kort uw vordelen:
				%ul.check-list
					%li RVS OF ALU frame buigen wij zelf
					%li Luxe RVS beslag
					%li Ruimte keuze uit beste kwaliteit doeken zoals Sunbrella, Mrakilux
					%li Opberghoes van hetzelfde stof altijd bij geleverd
					%li Buis tunnels Standaard voorzien van ritsen
					%li Supportpolses in optie voor maar 89 €
					%li inclusief alle bevestiging materiaal
					%li Biminitop wordt op maat gemaakt aan uw wensen
					%li Levertijd 2 weken
/ %section#portfolio
/ 	.container
/ 		%ul#portfolio-list.isotope
/ 			- @images.each do |image|
/ 				%li.one-third.column.item.branding.isotope-item{ :style => "position:relative" }
/ 					= link_to "", "as", :class => "isotope"
/ 					%figure
/ 						= link_to "", "as", :class => "isotope"
/ 						.hold.big
/ 							= link_to "asx", :class => "isotope" do
/ 								= image_tag image.gsub("public/images/", ""), :alt => "aaa"
/ 							= link_to "sxsx", :class => "hover-zoom swipebox" do
/ 								%i.icon-search
/ 							= link_to "sdxsadx", :class => "hover-link" do
/ 								%i.icon-link
/ 						%figcaption.item-description
/ 							%h5 Image
/ 							%span Description

app/views/pages/buiskap.html.haml
.page-title
	.container
		.twelve.columns
			%h1 Buiskap
		%nav.four.columns
			%ul.breadcrumbs
				%li
					= link_to "Home", "/"
				%li
					%i.icon-angle-right
				%li Buiskap
%section#typography
	.container
		.sixteen.columns
			%article
				%h2 Buiskap
				%p
					Door ons op maat gemaakte buiskappen zijn van beste kwaliteit, passen perfect in form, en zijn stevig afgewerkt.

				%p
					Voor onze alle boottenten, sprayhoods, cabriokappen worden top merken stoffen gebruikt, RVS buizen en alle RVS beslag. Deze combinatie zorg voor zeer mooie uitstraling van jou boottent.

				%p
					Voor elke buiskap wordt mal op de boot gemaakt. Daarna bespreken wij altijd de wensen en mogelijkheden met de klant.

				%p
					Uiteindelijk wordt de buiskap op jouw boot gemonteerd.
			%article
				%p
					Voordelen:
				%ul.check-list
					%li RVS of ALU Frame
					%li luxe RVS Beslag
					%li strak opgespannen
					%li Top kwaliteit doeken Sunbrella
					%li Bevestigd met tenax, minax, drukknoppen
					%li stevig afgewerkt
					%li Snel geleverd, meestaal binnen 2 weken
/ %section#portfolio
/ 	.container
/ 		%ul#portfolio-list.isotope
/ 			- @images.each do |image|
/ 				%li.one-third.column.item.branding.isotope-item{ :style => "position:relative" }
/ 					= link_to "", "as", :class => "isotope"
/ 					%figure
/ 						= link_to "", "as", :class => "isotope"
/ 						.hold.big
/ 							= link_to "asx", :class => "isotope" do
/ 								= image_tag image.gsub("public/images/", ""), :alt => "aaa"
/ 							= link_to "sxsx", :class => "hover-zoom swipebox" do
/ 								%i.icon-search
/ 							= link_to "sdxsadx", :class => "hover-link" do
/ 								%i.icon-link
/ 						%figcaption.item-description
/ 							%h5 Image
/ 							%span Description

app/views/pages/home.html.haml
- if @slides.present?
  .fullwidthbanner-container
    .fullwidthbanner
      %ul
        - @slides.media.each do |slide|
          %li{ :data => { :transition => 'slideleft', :delay => '5000', :masterspeed => '500' } }
            = image_tag slide.attachment.url, :alt => slide.title
            .caption.large_thin.white.sft{ :data => { :x => '565', :y => '230', :speed => '500', :start => '1100', :easing => 'easeOutExpo' } }
              %p= slide.title
%section#typography
  .container
    .two-thirds.columns
      %ul.serviceboxes
        %li
          =link_to "/offerte-online", class: "service-icon" do
            = image_tag "icons/unused/file.png", :alt => "Offerte online" 
          %h3=link_to "Offerte online", "/offerte-online"
        %li
          =link_to "/werkgebied", class: "service-icon" do
            = image_tag "icons/unused/map.png", :alt => "Werkgebied" 
          %h3=link_to "Werkgebied", "/werkgebied"
        %li
          =link_to "/kleurenstaal", class: "service-icon" do
            = image_tag "icons/unused/book.png", :alt => "Kleurenstaal" 
          %h3=link_to "Kleurenstaal", "/kleurenstaal"
  .promobar
    .container
      = raw @page.content
  .container
    <div class="ten columns elements">
    <h3>Waarom Marine Stofferingen?</h3>    
    <div class="accordion-container">
    <ul class="accordion">
    - if @advantages.any?
      - @advantages.each do |advantage|
        %li
          %a= advantage.title
          = raw advantage.content         
    </ul>
    </div>      
    </div>
    <div class="six columns">
    <section class="testimonials elements">
    <h3>Nieuws</h3>
    <div id="quote_wrap" style="height: 222px;">
    - if @posts.any?
      - @posts.each do |post|
        %blockquote.quote
          .bubble
            = raw post.content
            .quote-author= post.published_at.strftime("\%d.\%m.\%Y")
    </div>
    </section>
    </div>
  .container
    .two-thirds.columns
    - if @products.any?
      .carousel-intro
        %h3 De producten
        .clearfix
      %section.jcarousel.recent-work-jc
        %ul          
        - @products.each do |product|
          %li.four.columns
            = link_to product.slug, :class => "recent-item" do
              %figure
                .hold.medium
                  - if product.media.any?
                    = image_tag product.media.first.attachment.url(:gallery_thumb), :alt => product.title
              %figcaption.item-description
                %h5= product.title
/ %section#portfolio
/   .container
/     %ul#portfolio-list.isotope
/       - @images.each do |image|
/         %li.one-third.column.item.branding.isotope-item{ :style => "position:relative" }
/           = link_to "", "as", :class => "isotope"
/           %figure
/             = link_to "", "as", :class => "isotope"
/             .hold.big
/               = link_to "asx", :class => "isotope" do
/                 = image_tag image.gsub("public/images/", ""), :alt => "aaa"
/               = link_to "sxsx", :class => "hover-zoom swipebox" do
/                 %i.icon-search
/               = link_to "sdxsadx", :class => "hover-link" do
/                 %i.icon-link
/             %figcaption.item-description
/               %h5 Image
/               %span Description

app/views/pages/loungekussens.html.haml
.page-title
	.container
		.twelve.columns
			%h1 Loungekussens
		%nav.four.columns
			%ul.breadcrumbs
				%li
					= link_to "Home", "/"
				%li
					%i.icon-angle-right
				%li Loungekussens
%section#typography
	.container
		.sixteen.columns
			%article
				%h2 Loungekussens
				%p
					Kussens op maat voor tuinmeubels. Loungeussens zijn uiteraad gemaakt van goede kwaliteit stoffen. Zeer geschikt voor boten, steigerhout banken. Koudschuim die wij gebruiken HR35 zorg voor goede veering, comfortable zitten en duurzamheid. Zulke voelling kan zo'n 8 jaar tegen de zware belasting zelfs in horeca toepassingen.

				%p
					Loungekussens zijn standaard strak over de voeling, afgewerkt met zijnaad. Achterin zijn onze kussens vorzien van de rits, voor makkelijk onderhoud en wassen.

				%p
					kussens zijn altijd op maat gemaakt, je hebt ruimte keuze uit veel kleuren en kwaliteit.

				%p
					Sunbrella of Sunproof stooffen zijn waterafstottend, en verkluren niet op de zon.
					Op onze kussens is uiteraad 24 manden garantie op stiksel en ritsen, en 5 jaar fabrikantgarantie op stof.
			%article
				%h2
					Voordelen:
				%ul.check-list
					%li op maat gemaakt
					%li snele levering
					%li ruimte keuze uit sunbrella en sunproof doeken
					%li top kwaliteit voeling
					%li Stewig afgewerkt
					%li Straak opgespannen
				%p
					%strong Grotere bestelling?
					Dan krijg jij altijd een korting!!!
				%p
					%strong Voorbeld prijs
					zitkussen 180x60x5 met sunbrella stof, hr35 schuim kost 125€

/ %section#portfolio
/ 	.container
/ 		%ul#portfolio-list.isotope
/ 			- @images.each do |image|
/ 				%li.one-third.column.item.branding.isotope-item{ :style => "position:relative" }
/ 					= link_to "", "as", :class => "isotope"
/ 					%figure
/ 						= link_to "", "as", :class => "isotope"
/ 						.hold.big
/ 							= link_to "asx", :class => "isotope" do
/ 								= image_tag image.gsub("public/images/", ""), :alt => "aaa"
/ 							= link_to "sxsx", :class => "hover-zoom swipebox" do
/ 								%i.icon-search
/ 							= link_to "sdxsadx", :class => "hover-link" do
/ 								%i.icon-link
/ 						%figcaption.item-description
/ 							%h5 Image
/ 							%span Description

app/views/pages/materialen.html.haml
<div class="container">
.page-title
  .container
    .twelve.columns
      %h1= @page.title
    %nav.four.columns
      %ul.breadcrumbs
        %li
          = link_to "Home", "/"
        %li
          %i.icon-angle-right
        %li= @page.title
<div class="sixteen columns">
= raw @page.content
</div>
</div>
- if @materials.any?
  - @materials.each do |article|
    .container
      .sixteen.columns.typography
        %hr
        %h3= article.title
        = raw article.content
    - if article.media.any?      
      - @media = article.media
      = render 'pages/gallery4'

app/views/pages/show.html.haml
= render 'layouts/top'
= render @page.template

app/views/pages/templates/_about.html.haml
<section class="about">
- if @page.media.any?  
  - @slider = "<div id=\"slider\" class=\"swipe\">\r\n<ul class=\"swipe-wrap\">"
  - @page.media.each do |image|
    - @slider << "<li><img src=\"#{image.attachment.url(:gallery_thumb)}\" alt=\"\" /></li>\n\r"
  - @slider << "</ul>\r\n<div class=\"swipe-navi\">\r\n<div class=\"swipe-left\" onclick=\"mySwipe.prev()\"><i class=\"icon-chevron-left\"></i></div>\r\n"
  - @slider << "<div class=\"swipe-right\" onclick=\"mySwipe.next()\"><i class=\"icon-chevron-right\"></i></div>\r\n</div>\r\n</div>"
= raw @page.content.sub('[slider]',@slider)
</section>

app/views/pages/templates/_standard.html.haml
%section#typography
  = raw @page.content
- if @page.media.any?
  = render 'pages/gallery'